postgres:
  image: postgres:9.6
  environment:
    - POSTGRES_USER=reports
    - POSTGRES_PASSWORD=reports
  volumes:
    - ./pgdata:/var/lib/postgresql/data
koboreports:
  build: .
  ports:
    - "5000:5000"
  environment:
    - DATABASE_URL=postgres://reports:reports@postgres/reports
    - PORT=5000
    - DEBUG=True
    - KPI_URL=https://kf.master.kbtdev.org/
    - KPI_API_KEY=forDevelopmentOnlyOKforDevelopmentOnlyOKforDevelopmentOnlyOK
    - KOBOCAT_URL=https://kc.master.kbtdev.org
    - SECRET_KEY=notVerySecure
  links:
    - postgres
