services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=reports
      - POSTGRES_PASSWORD=reports
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  koboreports:
    build: .
    # If hosting KoBoToolbox locally, set this to match your /etc/hosts record
    # so that the hostname will resolve correctly inside the Docker container
    # extra_hosts:
    # - kf.kobo.local:172.17.0.1
    environment:
      - KPI_URL=http://kf.kobo.local/
      # You MUST change these keys for a production environment!
      - KPI_API_KEY=forDevelopmentOnlyOKforDevelopmentOnlyOKforDevelopmentOnlyOK
      - SECRET_KEY=notVerySecureGenerateYourOwnRandomly
      # For local development only, it might be helpful to disable Django's
      # hostname checking. DO NOT DO THIS IN PRODUCTION!
      # - ALLOWED_HOSTS=*
      # Optional Sentry logging of Python exceptions
      # - SENTRY_DSN=http://your/sentry/dsn
      - DATABASE_URL=postgres://reports:reports@postgres/reports
      # If you change the port, update the devServer proxy setting
      # in webpack.config.js
      - PORT=5000
      # MUST be set to False for production deployments
      - DEBUG=True
    volumes:
      - ./:/app
    depends_on:
      # This won't guarantee that Postgres is actually ready to service requests
      # before starting the application, but it will ensure that the hostname
      # `postgres` resolves within the `koboreports` container.
      - postgres
    ports:
      - "5000:5000"
