name: koboreports
channels:
  - r
dependencies:
  - pandas
  - pip
  - pyasn1
  - pyopenssl
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-rmarkdown
  - r-tidyr
  - r-whisker

  - pip:
    - Django==1.11.29
    - Markdown==3.3.4
    - dj-database-url==0.5.0
    - django-private-storage==2.2.2
    - djangorestframework==3.11.2
    - gunicorn==20.1.0
    - psycopg2==2.8.6
    - raven==6.10.0
    - requests==2.25.1
    - unicodecsv==0.14.1
    - urllib3[secure]
    - whitenoise==3.3.1
    - xlrd==2.0.1
    - xlwt==1.3.0
