# Example use of rCharts

I want to show that it's easy to get interactive graphics using `rCharts`. This [documentation](https://media.readthedocs.org/pdf/rcharts/latest/rcharts.pdf) was particularly helpful in figuring out how to embed graphics inline.

```{r, results='asis', comment=NA}
library(rCharts)

hair_eye_male <- subset(as.data.frame(HairEyeColor), Sex == "Male")

n1 <- nPlot(Freq ~ Hair, group="Eye", data=hair_eye_male, type="multiBarChart")
n1$show('inline', include_assets=TRUE, cdn=TRUE)
```

I pulled a bunch more examples from this [demo](http://ramnathv.github.io/posts/rcharts-nvd3/index.html).

```{r, results='asis', comment=NA}
my.print <- function(g) g$print(include_assets=TRUE, cdn=TRUE)

dat <- data.frame(
  t = rep(0:23, each = 4), 
  var = rep(LETTERS[1:4], 4), 
  val = round(runif(4*24,0,50))
)
p8 <- nPlot(val ~ t, group =  'var', data = dat, 
 type = 'stackedAreaChart', id = 'chart'
)
my.print(p8)

p1 <- nPlot(mpg ~ wt, group = 'cyl', data = mtcars, type = 'scatterChart')
p1$xAxis(axisLabel = 'Weight (in lb)')
my.print(p1)

p4 <- nPlot(~ cyl, data = mtcars, type = 'pieChart')
my.print(p4)

p5 <- nPlot(~ cyl, data = mtcars, type = 'pieChart')
p5$chart(donut = TRUE)
my.print(p5)

data(economics, package = 'ggplot2')
p6 <- nPlot(uempmed ~ date, data = economics, type = 'lineChart')
my.print(p6)
```
