# Generated by Django 3.2 on 2021-05-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_rendering__unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendering',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rendering',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rendering',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='userexternalapitoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
