# Generated by Django 3.2 on 2021-05-04 03:07

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('equitytool', '0007_form_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='csv_form',
            field=models.TextField(blank=True, default='', help_text='Always overwritten by `xls_form`'),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='xls_form',
            field=private_storage.fields.PrivateFileField(default=None, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=''),
        ),
    ]
