name: Build and push *base* image to Docker Hub

on:
  push:
    # Don't waste time building every push: consider only tags, which are
    # usually releases
    tags:
      - '*'

jobs:
  docker-base-image-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kobotoolbox/reports_base
          # Use the Git tag for the Docker image tag (done automatically), and
          # additionally tag the new image as `latest`
          addLatest: true
          registry: docker.io
          dockerfile: Dockerfile.base
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
