name: Build and push *base* image to Docker Hub

on:
  push:
    # Don't waste time building every push: consider only tags, which are
    # usually releases
    tags:
      - '*'

jobs:
  docker-base-image-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kobotoolbox/reports_base
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile.base
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
